name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
      branches: [main]
      types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install backend dependencies
        run: npm install

      - name: Install frontend dependencies
        working-directory: frontend
        run: npm install

      - name: lint
        run: npm run lint

      - name: build
        working-directory: frontend
        run: npm run build

      - name: e2e tests
        uses: cypress-io/github-action@v5
        env:
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
        with:
          command: npm run test:e2e
          start: npm run start, npm run start-frontend
          wait-on: http://localhost:3001, http://localhost:3000

  deploy:
    name: Deploy to Render
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-20.04
    needs: simple_deployment_pipeline
    steps:
      - name: Trigger Render deployment
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.MY_RENDER_SERVICE_ID }}
          api-key: ${{ secrets.MY_RENDER_API_KEY }}

  tag_release:
    name: Add tag
    if: ${{ github.event_name == 'push' && !contains(toJson(github.event.commits.*.message), '#skip') }}
    runs-on: ubuntu-20.04
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@a2c70ae13a881faf2b4953baaa9e49731997ab36
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

  notify_success:
    name: Discord Webhook Notify - Success
    if: ${{ needs.tag_release.result == 'success' }}
    runs-on: ubuntu-20.04
    needs: tag_release
    steps:
      - uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: info
          details: Deployment succeeded!

  notify_failure:
    name: Discord Webhook Notify - Failure
    if: ${{ needs.tag_release.result == 'failure' || needs.tag_release.result == 'cancelled' }}
    runs-on: ubuntu-20.04
    needs: tag_release
    steps:
      - uses: rjstone/discord-webhook-notify@v1.0.4
        with:
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          severity: error
          details: Deployment failed.